solve lucky number task;
iamr0man/excercism pull request #12
Opened 2022-11-22 08:12 UTC by iamr0man

2022-11-22 11:16 UTC, Rastopyr requested changes

2022-11-22 11:16 UTC, Rastopyr commented on Lucky Numbers/script.js
> +	return Number(array1.join('')) + Number(array2.join(''))
`twoSum([1.1, 2.5], [4.99, 109.88])`

з такими цифрами буде помилка

2022-11-22 11:16 UTC, Rastopyr commented on Lucky Numbers/script.js
> +export function luckyNumber(value) {
Якщо це працює то ок, але задача з зірочкой:

- як перевірити на паліндром без спліту строки
- як перевірити на паліндром без перевода в строку

2022-11-23 08:25 UTC, iamr0man commented on Lucky Numbers/script.js
> +	return Number(array1.join('')) + Number(array2.join(''))
а як ти уявляешь додавання чисел з плаваючою точкою?
`[1, 2] + [4, 109] === 12 + 4109`
`[1.1, 2.5] + [4.99, 109.88] === ?? + ??` - це або огруглення чисел, або приберання точки щоб вишло - `[11, 25], [499, 10988]`

2022-11-28 12:26 UTC, Rastopyr commented on Lucky Numbers/script.js
> +	return Number(array1.join('')) + Number(array2.join(''))
Це так задача була поставлена?
Я просто дивлюся на контракт функціі і розумію що там може будь який інпут

2022-11-28 16:22 UTC, iamr0man commented on Lucky Numbers/script.js
> +	return Number(array1.join('')) + Number(array2.join(''))
задача не включала в себе цифри з плавачою точкою, бо іншому я би не пройшов би тести

2022-11-28 16:53 UTC, Rastopyr commented
@iamr0man а ти рішення з паліндромом сам війнашов чи загуглив?

2022-11-28 17:05 UTC, iamr0man commented
я знав що це можна зробити було через відсотки, тому що вирішували подібні задачі в колледжі, але не міг згадати і яким саме чином. тому заюзав гуглове

2022-11-28 17:06 UTC, Rastopyr approved these changes

2022-11-28 19:13 UTC, merged