solve function tasks;
iamr0man/excercism pull request #13
Opened 2022-11-22 08:25 UTC by iamr0man

2022-11-22 11:17 UTC, Rastopyr commented on  Lasagna Master/script.js
> +export function cookingStatus(remainingTime) {
Круто що зробив через switch!

2022-11-22 11:20 UTC, Rastopyr requested changes

2022-11-22 11:20 UTC, Rastopyr commented on  Lasagna Master/script.js
> +	const currentLayerQuantity = acc[currentLayer]
Обидві константи можут бути `undefiend`

2022-11-22 11:20 UTC, Rastopyr commented on  Lasagna Master/script.js
> +	}, { ...recipe })
nit: тут немає потреби дублювати recipe

2022-11-22 11:20 UTC, Rastopyr commented on  Lasagna Master/script.js
> +function quantityAccumulator(acc, currentLayer) {
nit: `quantityReducer`

2022-11-28 16:38 UTC, iamr0man commented on  Lasagna Master/script.js
> +	const currentLayerQuantity = acc[currentLayer]
переніс константу вгору і перевіряю, якщо в нашому списку немає що додавати - я повератаю накопичувач. оновив

2022-11-28 16:57 UTC, Rastopyr requested changes

2022-11-28 16:57 UTC, Rastopyr commented on  Lasagna Master/script.js
> +	const currentLayerQuantity = acc[currentLayer]
```js
if (!extraQuantity || !currentLayerQuantity) {
  return acc;
}
```

2022-11-28 16:57 UTC, Rastopyr commented on  Lasagna Master/script.js
> +	}, recipe)
Я мав на увазі, що достатьно було пустого обждекта

2022-11-28 16:59 UTC, iamr0man commented on  Lasagna Master/script.js
> +	const currentLayerQuantity = acc[currentLayer]
якщо extraQuantity не буде, немає сенсу далі робити перевірку - тому що далі теж буде undefined

2022-11-28 17:00 UTC, iamr0man commented on  Lasagna Master/script.js
> +	}, recipe)
а як буде проходити ітерація через пустий обʼєкт ?

2022-11-28 17:02 UTC, iamr0man commented on  Lasagna Master/script.js
> +	}, recipe)
а соррі, не туди дивився

2022-11-28 17:09 UTC, Rastopyr requested changes

2022-11-28 17:09 UTC, Rastopyr commented on  Lasagna Master/script.js
> +	const currentLayerQuantity = acc[currentLayer]
- з точки зору системі типів і там і там може буте undefined
- та залежність про яку ти говориш, вона не обозначена в коді
- може бути `extraQuantity` але може не бути `currentLayerQuantity`

2022-11-29 09:14 UTC, Rastopyr approved these changes

2022-11-29 10:13 UTC, merged