add Coordinate Transform tasks;
iamr0man/excercism pull request #15
Opened 2022-11-22 21:09 UTC by iamr0man

2022-11-28 16:30 UTC, iamr0man commented
скоріш за все, що я перестарався в останній задачі. бо як я подивився - рішення було доволі простіше. але я покриваю тут більшу логіку обробки

2022-12-03 10:39 UTC, Rastopyr requested changes

2022-12-03 10:39 UTC, Rastopyr commented on Coordinate Transform/script.js
> +export function memoizeTransform(f) {
Це не мемоізація, тут запамятовується тільки останне виконання функції.

2022-12-04 20:02 UTC, iamr0man commented on Coordinate Transform/script.js
> +export function memoizeTransform(f) {
я спочатку реалізував по іншому, так як в останньому комміті, але в вправі спецефічні тести були

2022-12-04 20:23 UTC, Rastopyr approved these changes

2022-12-04 21:29 UTC, merged