Promise
iamr0man/excercism pull request #24
Opened 2022-12-09 12:21 UTC by iamr0man

2022-12-09 12:23 UTC, iamr0man commented on Translation Service/service.js
> +	}
зробив схожу реалізцію, як ми робили в попередній задачі. все окей, робить рекурсивні запити - але не повертається відповідь. ні реджект, ні резолв.

2022-12-09 13:25 UTC, Rastopyr requested changes

2022-12-09 13:25 UTC, Rastopyr commented on Translation Service/service.js
> +	}
1. Подивись чи правильний в тебе порядок `.then`/`.catch`
2. В catch просто повертається рекурсівний запит. Має бути promise.
3. Перший promise тут не потрбен, бо this.api.fetch повертає promise як є.

Пропоную подивитися відос, та спробувати в codesandbox пограти з тім кодом що пише чувак на відео.
https://www.youtube.com/watch?v=DHvZLI7Db8E

Якщо зручніше текстом, то ось непогані матеріали:
https://web.dev/promises/#chaining
https://javascript.info/promise-basics
https://www.programiz.com/javascript/promise

2022-12-11 11:46 UTC, Rastopyr requested changes

2022-12-11 11:46 UTC, Rastopyr commented on Translation Service/service.js
> +				return new Promise((resolve, reject) => {
Тут наче теж зайвий Promise. Якщо в catch повертати promise, то він буде частиною цепочки промізов.

2022-12-13 09:11 UTC, Rastopyr requested changes

2022-12-13 09:11 UTC, Rastopyr commented on Translation Service/service.js
> +					.then((result) => Promise.resolve(result))
Promise.resolve та Promise.reject тут не потрібні, бо значення і так буде резолвітися, а помилка реджектетися

2022-12-13 09:11 UTC, Rastopyr commented on Translation Service/service.js
> +			resolve(Promise.all(promises).then((value) => value))
Давай цей метод спробуємо порефакторить. Є ідеї що можно було б покращити?

2022-12-13 09:11 UTC, Rastopyr commented on Translation Service/service.js
> +	counter = 0
Це вже зайвий проперті

2022-12-14 10:31 UTC, Rastopyr requested changes

2022-12-14 10:31 UTC, Rastopyr commented on Translation Service/service.js
> +		return new Promise((resolve, reject) => {
Все ще можна покращити цей код.

Підкажи будь ласка, ти вже дивися відоси/читав статті яки я тобі кидав?

2022-12-21 14:56 UTC, Rastopyr requested changes

2022-12-21 14:56 UTC, Rastopyr commented on Translation Service/service.js
> +		return new Promise((resolve, reject) => {
Ти пізніше виправиш цю частину?

2022-12-21 14:56 UTC, Rastopyr commented on Translation Service/service.js
> +		const promisify = () => {
Тут все ок було з назвою, як на мою думку

2022-12-25 09:30 UTC, Rastopyr approved these changes

2022-12-25 20:11 UTC, merged