add No space left on device task;
iamr0man/excercism pull request #31
Opened 2022-12-21 12:18 UTC by iamr0man

2022-12-21 12:42 UTC, Rastopyr requested changes
-

2022-12-21 13:49 UTC, iamr0man commented
updated

2022-12-21 14:49 UTC, Rastopyr requested changes

2022-12-21 14:49 UTC, Rastopyr commented on No Space Left On Device/script.js
> +	if (isFile) {
Цей код можно покращити.

- тобі непотрібно зберегати данні про файли, а тільки про розмір діректорій
- наскільки я зрозумів, то ти будуеш спражвній граф, але це може бути занадто для задачи. є більш проста та дієва структура це linked list. для оптимизаціі це може бути не ліст а обжект/мапа

2022-12-21 15:17 UTC, iamr0man commented on No Space Left On Device/script.js
> +	if (isFile) {
- розмір директорії будується ж від розмірів файлів всередині
- не розумію чому потрібен linked list, якщо в нього немає доступу до попереднього єлементу єлементу, він є в дабл лінкед листі

2022-12-21 15:20 UTC, Rastopyr commented on No Space Left On Device/script.js
> +	if (isFile) {
1. Ну, тобто інфу про самі файли зберегати не потрібно
2. Ну фактично тобі потрібна інфа про діректорію та її родітеля, цього достатьно щоб ефективно все порахувати

2022-12-21 15:24 UTC, iamr0man commented on No Space Left On Device/script.js
> +	if (isFile) {
можна типу будувати і опиратись на path (/folder/folder1) и по ньому бігати слайсами, але мені здається, що мій варінт більше зрозуміліший

2022-12-21 16:02 UTC, Rastopyr commented on No Space Left On Device/script.js
> +	if (isFile) {
Спробуєш порефакторіти використовуючи тільки ось ці два тіпа данних?

```
type FolderInfo = {
  readonly size: number;
  readonly parentFolder: string;
  readonly name: string;
}
type FoldersInfo = Record<string, FolderInfo>
```

2022-12-21 16:16 UTC, iamr0man commented on No Space Left On Device/script.js
> +	if (isFile) {
плюс мінус так і зробив

2022-12-21 16:33 UTC, Rastopyr requested changes
Вже краще, та виглядає набагато простіше.

Залишив пару коментарів.

---

Загалом, оптимальне рішення, це те яке не робе зайву роботу, щоб знайти відповідь. Всі ці алгорітмічни челенджи направлени саме на це.

З такой позиції пошук парент діректорії може бути порахований заздалегідь, бо по логам ти ідеш з парент діректоріі в чайлд діректорію, і відповідно що коли створюється об'ект чайлда , парент можно просто записати як посилання.

Таким чином, processEntry не буде щоразу парсить парента при оновлені розміра діректорії, а просто бігти як по linked list. 

Теж саме і з processCommand

---

Також я би запропонував зробити скоуп программи не глобальним, та винести всю логіку в редьюс.

2022-12-21 16:33 UTC, Rastopyr commented on No Space Left On Device/script.js
> +		.reduce((path, directory, index) => {
Можно уникнути маніпуляцій зі строками якщо зберегати для кожной діректоріі посилання на парента та рекурсівно обходити кожного.

2022-12-21 16:33 UTC, Rastopyr commented on No Space Left On Device/script.js
> +let currentDirectory = '';
Для рішення це ок, але це постійні мутації глобального контексту. Давай зробимо це через reduce стейту?

2022-12-21 16:33 UTC, Rastopyr commented on No Space Left On Device/script.js
> +function processLine(line) {
nit: порядок функцій не збігається зі скоупом. працює через хоістінг, але це неявно відбувається. був би лінтер, він б на це ругнувся

2022-12-21 16:33 UTC, Rastopyr commented on No Space Left On Device/script.js
> +function getParentDirectory (currentDirectory, path) {
Потрібне посилання на парент діректорію, і не буде потрібен ось цей парсінг

2022-12-21 16:51 UTC, iamr0man commented on No Space Left On Device/script.js
> +		.reduce((path, directory, index) => {
тоді, це ж не ліндек ліст виходить

2022-12-21 16:52 UTC, Rastopyr commented on No Space Left On Device/script.js
> +		.reduce((path, directory, index) => {
Чому?

2022-12-25 09:26 UTC, Rastopyr approved these changes

2022-12-25 20:11 UTC, merged