add Poetry Club Door Policy task;
iamr0man/excercism pull request #4
Opened 2022-11-10 17:01 UTC by iamr0man

2022-11-10 17:38 UTC, Rastopyr requested changes
Кожна функція, враховуючи type description приймає рядок, та має теж повертати рядок.

Але треба врахувати що може прийти, наприклад, пустий рядок.

2022-11-10 17:38 UTC, Rastopyr commented on Poetry Club Door Policy/script.js
> + export function frontDoorResponse(line) {
Давай спробуємо врахувати, що input може бути різноманітний. Наприклад пустий рядок.

2022-11-10 17:38 UTC, Rastopyr commented on Poetry Club Door Policy/script.js
> +  export function frontDoorPassword(word) {
Тут теж може бути пустий рядок

2022-11-14 10:11 UTC, Rastopyr requested changes
Чому ти обрав шлях черех екзепшг? Мені здається що в багатьох моментах це порушує логіку функціі

2022-11-14 18:35 UTC, iamr0man commented
як краще описати цю логіку? є декілька варінтів - повертати порожню рядок, повертати undefined чи кидати помилку (тому що ми не пройшли домовленність методу і вписали пустий рядок)

2022-11-14 18:38 UTC, Rastopyr commented
Я би обрав шлях де ми повертаємо пустий рядок. Це буде відповідати опису функціі, і теоретично буде валідним. Перший пункт від пустого рядка це пустий рядок

2022-11-15 08:16 UTC, iamr0man commented
`''[0] === undefined // true` - можу посперичатись

2022-11-15 08:40 UTC, Rastopyr commented
> `''[0] === undefined // true` - можу посперичатись
> 
> 

Це з точки зору мови програмування та імплементації там undefined. Тут ти правий. 

Але з боку контракта функції, вона завжди має повертати string, з чого можно припустити логіку яку я описав вищче.

2022-11-15 12:15 UTC, Rastopyr approved these changes

2022-11-15 12:31 UTC, iamr0man commented
окей, дякую для розяснення!

2022-11-19 08:33 UTC, merged