add Elyses Enchantments task;
iamr0man/excercism pull request #5
Opened 2022-11-10 17:01 UTC by iamr0man

2022-11-11 13:43 UTC, Rastopyr requested changes
`shift`/`splice`/`unshift`/`push`/`pop` роблять мутації над списком.

Все ок, але спробуй зробити теж саме і через immutable підхід.

2022-11-12 12:15 UTC, iamr0man commented
я так і робив спочатку (записував в нову змінну массиву и повертав оновлену копію), але по тестам не пройшло - тому що вони передадають массив (обʼєкт) і в результаті хочуть його мутаціі.

2022-11-12 12:45 UTC, iamr0man commented
updated

2022-11-14 10:42 UTC, Rastopyr requested changes

2022-11-14 10:42 UTC, Rastopyr commented on Elyses Enchantments/script.js
> + export function getItem(cards, position) {
Тут `getItem` може повернути undefiend

2022-11-14 10:42 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +  export function setItem(cards, position, replacementCard) {
Тут можно робити через `.map`

2022-11-14 10:42 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +    const copyCards = [...cards]
`return [...cards, newCard]`

2022-11-14 10:42 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +  export function removeItem(cards, position) {
Тут можно робити через `filter`

2022-11-14 10:42 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +  export function removeItemFromTop(cards) {
Тут можно робити через `filter`

2022-11-14 10:42 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +  export function removeItemAtBottom(cards) {
```
const [_, ...rest] = cards;
return rest;
```

2022-11-14 10:42 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +  export function insertItemAtBottom(cards, newCard) {
`return [newCard, ...cards]`

2022-11-14 18:14 UTC, iamr0man commented on Elyses Enchantments/script.js
> + export function getItem(cards, position) {
потрібно тоді додати underfiend як можливий результат функціі

2022-11-14 18:16 UTC, iamr0man commented on Elyses Enchantments/script.js
> +  export function setItem(cards, position, replacementCard) {
навіщо проходити весь массив, щоб засетити один елемент ?

2022-11-14 18:20 UTC, iamr0man commented on Elyses Enchantments/script.js
> +  export function setItem(cards, position, replacementCard) {
а я зрозумів твоє завдання - `shift`/`splice`/`unshift`/`push`/`pop` роблять мутації над списком.

2022-11-14 18:24 UTC, iamr0man commented on Elyses Enchantments/script.js
> +  export function setItem(cards, position, replacementCard) {
я думав, що ти маєш на увазі мутації вихідного массиву даних (список). я тому і створюю копію списку, щоб не модифікувати цей самий вихідний массив.

2022-11-14 18:25 UTC, Rastopyr commented on Elyses Enchantments/script.js
> + export function getItem(cards, position) {
В данному випадку буде валідний екзепшн.

2022-11-14 18:26 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +  export function setItem(cards, position, replacementCard) {
Це фнукціональний підхід. Immutable data structure

2022-11-14 18:36 UTC, Rastopyr requested changes

2022-11-14 18:36 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +        cards[position] = replacementCard
Так як ти це зробив, це все ще мутація)

```
return cards.map((card, index) => position === index ? replacementCard : card)
```

2022-11-14 18:36 UTC, Rastopyr commented on Elyses Enchantments/script.js
> +        cards[position] = replacementCard
`cards[index]` це заміна елемента за індексом - тобто мутація.

`.map` повертає новий массів. за індексом ми бачимо що це той самий елемент, який треба замінити, і замість існуючего, повертаємо інший елемент.

2022-11-15 08:18 UTC, iamr0man commented on Elyses Enchantments/script.js
> +        cards[position] = replacementCard
блін, так, погоджуюсь

2022-11-15 12:15 UTC, Rastopyr approved these changes

2022-11-19 08:33 UTC, merged