add Vehicle Purchase task;
iamr0man/excercism pull request #6
Opened 2022-11-10 17:16 UTC by iamr0man

2022-11-11 13:57 UTC, Rastopyr requested changes

2022-11-11 13:57 UTC, Rastopyr commented on Vehicle Purchase/script.js
> +export function needsLicense(kind) {
Можемо припустити, що кількисть тіпив машин може тільки збільшуватися. Робити кожен раз `||` кондішен це не ок.

Є ідеі як це можно врахувати та переписати цю функцію?

2022-11-11 13:57 UTC, Rastopyr commented on Vehicle Purchase/script.js
> +export function calculateResellPrice(originalPrice, age) {
Зараз ця імплементація порушує Open-Closed principle.

Правил для розрахунку reseller price може бути десятки. Є ідеї як це можно врахувати в імплементації?

2022-11-12 12:16 UTC, iamr0man commented on Vehicle Purchase/script.js
> +export function needsLicense(kind) {
створити новий массив, де будемо перелічувати потрібні нам данні - і перевіряти через метод includes

2022-11-12 12:41 UTC, iamr0man commented on Vehicle Purchase/script.js
> +export function calculateResellPrice(originalPrice, age) {
так, є - зробив оновлене рішення

2022-11-19 12:58 UTC, Rastopyr requested changes

2022-11-19 12:58 UTC, Rastopyr commented on Vehicle Purchase/script.js
> +export function calculateResellPrice(originalPrice, age) {
Я взагалі думав над тім, щоб зберегати тільки коєффіціент а сам розрахунок вже робити в середині функціі.

2022-11-19 12:58 UTC, Rastopyr commented on Vehicle Purchase/script.js
> +	const [, result] = Object.entries(relationAgeToPrice).filter(([maxAge]) =>  age <= Number(maxAge))[0]
Мені здається що тут відбувається зайва робота. Розуміеш де саме?

2022-11-19 12:58 UTC, Rastopyr commented on Vehicle Purchase/script.js
> +export function calculateResellPrice(originalPrice, age) {
```typescript
type ResellPriceDecorator = {
  readonly checkAge: (age: number) => boolean;
  readonly modifyPrice: (price: number) => number;
}
```

2022-11-22 11:07 UTC, Rastopyr requested changes

2022-11-22 11:07 UTC, Rastopyr commented on Vehicle Purchase/script.js
> +export function calculateResellPrice(originalPrice, age) {
Ми на останньому дзвінку домовилися, що спробуємо зробити  цю логіку через інтерфейс `ResellPriceDecorator`, який написан в коменті вишче

2022-11-28 17:05 UTC, Rastopyr requested changes

2022-11-28 17:05 UTC, Rastopyr commented on Vehicle Purchase/script.js
> +	return modifyPrice()
Це ще не вирішуе проблему. Тут поки що багато логики, і сам обджект, він є в середині функціі

```
const relationAgeToPrice = [
 { checkAge: () => {...}, modifyPrice: () => {...} }
]
```

2022-11-29 09:13 UTC, Rastopyr approved these changes

2022-11-29 10:13 UTC, merged