add base loop operation;
iamr0man/excercism pull request #7
Opened 2022-11-15 08:36 UTC by iamr0man

2022-11-16 12:16 UTC, Rastopyr requested changes

2022-11-16 12:16 UTC, Rastopyr commented on Bird Watcher/script.js
> +export function totalBirdCount(birdsPerDay) {
nit: таки функціі краще писати в один рядок `(acc, curr) => acc, cur`

2022-11-16 12:16 UTC, Rastopyr commented on Bird Watcher/script.js
> +export function totalBirdCount(birdsPerDay) {
Чи наприклад: `.reduce(Math.sum, 0)`

2022-11-16 12:16 UTC, Rastopyr commented on Bird Watcher/script.js
> +			birdsPerDay[index] = birdCount + 1
тут знову мутація, мутіровати список з середини map операції неможна :)

2022-11-16 21:27 UTC, Rastopyr requested changes

2022-11-16 21:27 UTC, Rastopyr commented on Bird Watcher/script.js
> +		return index % 2 === 0 ? result.concat(birdCount + 1) : result.concat(birdCount)
У конката трішки інше призначеня, він має об'єднувати два список. Як створити новий список + додати елемент в кінец, ми вже робили на одном з прошлих уроков.

`result.concat(birdCount + 1)` -> `[...result, birdCount + 1]`

2022-11-16 21:27 UTC, Rastopyr commented on Bird Watcher/script.js
> +		return index % 2 === 0 ? result.concat(birdCount + 1) : result.concat(birdCount)
Це чисто коментарь до стилю, але на мою думку краще виносити в condition тільки те, що насправді змінюється, а потім все сводити до загальной логікі. Тобто в бранчах кондешена має бути тільки те, що стосується самого кондішена.

```
const fixCount = index % 2 === 0 ? 1 : 0;

return [...result, birdCount + fixCount]
```

2022-11-19 11:25 UTC, iamr0man commented on Bird Watcher/script.js
> +		return index % 2 === 0 ? result.concat(birdCount + 1) : result.concat(birdCount)
1. я тут використовував concat із-за того, що він повертає посилання на массив і може додавати звичайний елемент, але я так зрозумів, що це може конфюзити розробників.
2. тут погоджуюсь, доволі розумне рішення!

2022-11-19 13:02 UTC, Rastopyr approved these changes

2022-11-20 21:21 UTC, merged