add tasks with switch and while;
iamr0man/excercism pull request #8
Opened 2022-11-15 10:22 UTC by iamr0man

2022-11-16 12:33 UTC, Rastopyr requested changes

2022-11-16 12:33 UTC, Rastopyr commented on Mixed Juices/script.js
> +	while (needMoreWedges && isNotEndOfLimes && wedgesNeeded) {
while loop це була вимога урока?

питаю, бо це не дуже зрозуміло, принаймні для мене, написано.

- в ціклі використовується константа, яка розраховивається від змінной
- дві константи взагалі в цьому ціклі не змінюються

можливо краще використати інший цікл?

2022-11-16 20:28 UTC, iamr0man commented on Mixed Juices/script.js
> +	while (needMoreWedges && isNotEndOfLimes && wedgesNeeded) {
так, завдання було використати while loop

2022-11-16 21:33 UTC, Rastopyr requested changes

2022-11-16 21:33 UTC, Rastopyr commented on Mixed Juices/script.js
> +	while (needMoreWedges && isNotEndOfLimes && wedgesNeeded) {
`wedgesNeeded` - можно перевіряти раніше, бо вона не змінюється. це умова функціі а не циклу.

 `needMoreWedges` та `isNotEndOfLimes` я би заинлайніл. бо те що вони в константах але іх значеня має змінюватися поки працює цикл, це mind blowing.

в мене такой код наприклад в консолі не запрацював.

2022-11-19 11:34 UTC, iamr0man commented on Mixed Juices/script.js
> +	while (needMoreWedges && isNotEndOfLimes && wedgesNeeded) {
я теж не міг зрозуміти, чому він не працював в мої консолі, а тести пройшов на сайті. тепер зрозумів, що із-за констант, змінні не перечислювались.

2022-11-19 13:16 UTC, Rastopyr approved these changes

2022-11-20 21:22 UTC, merged