add object tasks;
iamr0man/excercism pull request #9
Opened 2022-11-17 18:26 UTC by iamr0man

2022-11-17 18:54 UTC, Rastopyr requested changes

2022-11-17 18:54 UTC, Rastopyr commented on High Score Board/script.js
> +export function addPlayer(scoreBoard, player, score) {
- Мутація об'екту.
- Що робити якшо гравец вже існує?

2022-11-17 18:54 UTC, Rastopyr commented on High Score Board/script.js
> +export function removePlayer(scoreBoard, player) {
- Мутація об'екту

2022-11-17 18:54 UTC, Rastopyr commented on High Score Board/script.js
> +	scoreBoard[player] += points
- Мутація об'екту
- Що робити якщо гравця не існує?

2022-11-17 18:54 UTC, Rastopyr commented on High Score Board/script.js
> +		scoreBoard[key] += BONUS_AMOUNT
- Мутація об'екту

2022-11-17 18:54 UTC, Rastopyr commented on High Score Board/script.js
> +export function normalizeScore(params) {
Ця функція тут виглядає якось дивно. Немає опису типу `Params`

2022-11-19 13:14 UTC, Rastopyr requested changes

2022-11-19 13:14 UTC, Rastopyr commented on High Score Board/script.js
> +		scoreBoardCopy[key] += BONUS_AMOUNT
`.entries().reduce(accFn, {})`

2022-11-20 21:35 UTC, Rastopyr requested changes

2022-11-20 21:35 UTC, Rastopyr commented on High Score Board/script.js
> +	newScoreBoard[key] = value + BONUS_AMOUNT
мутація, краще так

```
return {
  ...newScoreBoard,
  [key]: value + BONUS_AMOUNT
}
```

2022-11-20 21:38 UTC, iamr0man commented on High Score Board/script.js
> +	newScoreBoard[key] = value + BONUS_AMOUNT
чому таким чином краще?

2022-11-20 21:41 UTC, Rastopyr commented on High Score Board/script.js
> +	newScoreBoard[key] = value + BONUS_AMOUNT
- це immutable approach. тобто це працює якщо використвується всюди
- тут відбувається мутація аргумента
- мутація аргумента це не відображаеться в його контракті

2022-11-20 21:41 UTC, Rastopyr approved these changes

2022-11-20 21:50 UTC, merged